version: '3.8'
services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/app/src
      - waba_db:/app/storage
    env_file: .env
    ports:
      - '8000:8000'

volumes:
  waba_db:
